version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_al
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: seatwaves
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 30s
      timeout: 30s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_al
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
      - '5051:443'

  redis-stack:
    image: redis/redis-stack:7.4.0-v1
    ports:
      - '6379:6379'
      - '8002:8001'
    volumes:
      - redis-stack:/data
    environment:
      - REDIS_ARGS=--save 900 1

volumes:
  postgres:
  redis-stack:
